# Site settings
title: WinBetaUser
email: markta111@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  WinBetaUser 是一个 Windows 爱好者，是 WinBetaMUI Team 的队长。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  winbetauser
# facebook_username: jekyll
# google_play: 'GDGX'
# google_plus_com: '109485346959707049693'  # Community link
# google_plus_per: '+GDGManagua'  #Personal link
# facebook_app_id: 12345

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: 选项
    link: github.com/winbetauser

disqus: false
# disqus_shortname: 'gdgmanagua'

# Build settings
markdown: kramdown
